# Generated by Django 3.2.12 on 2022-03-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_departure', models.DateField(blank=True)),
                ('date_of_arrival', models.DateField(blank=True)),
                ('country_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_from', to='shipments.country')),
                ('country_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_to', to='shipments.country')),
            ],
        ),
    ]
