# Generated by Django 3.2.12 on 2022-03-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date_of_arrival',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date_of_departure',
            field=models.DateField(null=True),
        ),
    ]
