# Generated by Django 3.2.12 on 2022-03-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20220322_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date_of_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date_of_departure',
            field=models.DateField(blank=True, null=True),
        ),
    ]
